// Assemble the served app from src/ — run after ANY edit under src/:
//
//   node scripts/build.mjs           build once
//   node scripts/build.mjs --watch   rebuild on every src/ change
//
// Outputs (committed to the repo — GitHub Pages serves them as-is, zero-build):
//   index.html   from src/index.template.html   (small: markup only)
//   styles.css   from src/css/styles.css        (includes the GENERATED-DARK block)
//   app.js       src/js/app/*.js sorted, wrapped in one IIFE, + src/js/global/*.js after it
//   sw.js        from src/sw.template.js
//
// {{V}} placeholders become a content hash, so cache-busting is automatic:
// no more manual `yardsmith-vNNN` bumps or ?v= pin edits. Never edit the
// four outputs directly — they carry a GENERATED header and your change will
// be overwritten by the next build.
//
// Related: scripts/gen-dark-theme.py regenerates the dark theme INSIDE
// src/css/styles.css — run it after CSS changes, then run this build.

import { readFileSync, writeFileSync, readdirSync, watch } from "node:fs";
import { createHash } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src");

function partFiles(dir) {
  return readdirSync(join(SRC, dir)).filter(f => f.endsWith(".js")).sort()
    .map(f => ({ name: `${dir}/${f}`, code: readFileSync(join(SRC, dir, f), "utf8") }));
}

function build() {
  const app = partFiles("js/app");
  const globals = partFiles("js/global");
  const js =
    `/* GENERATED by scripts/build.mjs — edit src/js/**, not this file. */\n` +
    `(function () {\n  "use strict";\n\n` +
    app.map(p => `/* ────────── ${p.name} ────────── */\n${p.code}`).join("\n") +
    `\n})();\n\n` +
    globals.map(p => `/* ────────── ${p.name} ────────── */\n${p.code}`).join("\n");

  const css =
    `/* GENERATED by scripts/build.mjs — edit src/css/styles.css, not this file. */\n` +
    readFileSync(join(SRC, "css/styles.css"), "utf8");

  const tpl = readFileSync(join(SRC, "index.template.html"), "utf8");
  const swTpl = readFileSync(join(SRC, "sw.template.js"), "utf8");

  // Content hash across everything the client caches → automatic cache busting.
  const V = createHash("sha256").update(js).update(css).update(tpl).update(swTpl)
    .digest("hex").slice(0, 10);

  const html =
    tpl.replace("<!doctype html>", "<!doctype html>\n<!-- GENERATED by scripts/build.mjs — edit src/index.template.html, not this file. -->")
       .replaceAll("{{V}}", V);
  const sw =
    `/* GENERATED by scripts/build.mjs — edit src/sw.template.js, not this file. */\n` +
    swTpl.replaceAll("{{V}}", V);

  writeFileSync(join(ROOT, "app.js"), js);
  writeFileSync(join(ROOT, "styles.css"), css);
  writeFileSync(join(ROOT, "index.html"), html);
  writeFileSync(join(ROOT, "sw.js"), sw);
  console.log(`build: v=${V} · app.js ${(js.length/1024).toFixed(0)}k (${app.length} parts) · styles.css ${(css.length/1024).toFixed(0)}k · index.html ${(html.length/1024).toFixed(0)}k`);
}

build();

if (process.argv.includes("--watch")) {
  console.log("watching src/ …");
  let t = null;
  for (const dir of ["", "css", "js/app", "js/global"]) {
    watch(join(SRC, dir), () => {
      clearTimeout(t);
      t = setTimeout(() => { try { build(); } catch (e) { console.error(e.message); } }, 120);
    });
  }
}
